apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/rhtap-test-local/e2e-tests-remote?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-event: '[push]'
    pipelinesascode.tekton.dev/on-target-branch: '[storage-type-nvme]'
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: test-rhtap-30-app-fowge
    appstudio.openshift.io/component: test-rhtap-30-app-fowge-comp-0
    pipelines.appstudio.openshift.io/type: build
  name: test-rhtap-30-app-fowge-comp-0-on-push
  namespace: test-rhtap-30-tenant
spec:
  params:
  - name: dockerfile
    value: Dockerfile
  - name: git-url
    value: '{{repo_url}}'
  - name: output-image
    value: quay.io/redhat-user-workloads-stage/test-rhtap-30-tenant/test-rhtap-30-app-fowge/test-rhtap-30-app-fowge-comp-0:{{revision}}
  - name: path-context
    value: .
  - name: revision
    value: '{{revision}}'
  pipelineRef:
    name: build-pipeline
  taskRunTemplate:
    podTemplate:
      nodeSelector:
        konflux-ci.dev/storage: "nvme"
      priorityClassName: konflux-default
      tolerations:
        - key: konflux-ci.dev/storage
          operator: "Equal"
          value: "nvme"
          effect: "NoSchedule"
  workspaces:
    - name: workspace-amd64
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
    - name: git-auth
      secret:
        secretName: '{{ git_auth_secret }}'
